### ISSUE TITLE
Errors on the site ipdeny.com

### ISSUE THREAD

**Issue by henikolett** [markuskowa/ipdeny-zones#1]
Hi markuskowa!

Today I noticed that some country zone files on the website ipdeny.com are not complete, 
for example the fr.zone and de.zone files look like that content was cut from the file's end.

I tried to write a message using the contact form on that page, but didn't succeed, because the site just kept on loading.

Also, the all-zones.tar.gz file is corrupted too, it throws an "unexpected end of file" error when trying to unzip it.

I'm talking about the following files:
http://www.ipdeny.com/ipblocks/data/countries/all-zones.tar.gz
http://www.ipdeny.com/ipblocks/data/countries/fr.zone
http://www.ipdeny.com/ipblocks/data/countries/de.zone

And the blog page shows an "Error establishing a database connection" message, just noticed it.

I apprecite your work regarding these country zone files, I'm only curious about whether you plan to update the site in the future?

Thank you in advance!

Best regards,
Nikolett Hegedus

**Comment by markuskowa** [comment]
Hi Nikolett. Sorry for the late reply. I use the files for a firewall script. So I will update them once in a while.
